-- Produktionsdatabasen (neon-pink-lever) för linnevik.
-- Kör hela filen i Neons SQL-editor. Går att köra om: inget skrivs över.

CREATE TABLE IF NOT EXISTS "admin_activity" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "admin_activity_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"actor" text NOT NULL,
	"action" text NOT NULL,
	"target" text,
	"detail" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "client_contacts" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "client_contacts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"client_id" integer NOT NULL,
	"first_name" text NOT NULL,
	"last_name" text,
	"role" text,
	"email" text,
	"phone" text,
	"linkedin" text,
	"status" text DEFAULT 'Ej kontaktad' NOT NULL,
	"channel" text,
	"last_contacted_at" date,
	"next_action" text,
	"next_action_due" date,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "clients" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "clients_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"customer_no" text NOT NULL,
	"name" text NOT NULL,
	"segment" text,
	"status" text DEFAULT 'Tvätterikund' NOT NULL,
	"priority" text,
	"reminder_fee" numeric(10, 2),
	"name_truncated" boolean DEFAULT false NOT NULL,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS "price_suggestions" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "price_suggestions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user" text NOT NULL,
	"label" text,
	"prices" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

DO $$ BEGIN
  ALTER TABLE "client_contacts" ADD CONSTRAINT "client_contacts_client_id_clients_id_fk"
    FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE cascade;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS "client_contacts_client_id_idx" ON "client_contacts" USING btree ("client_id");
CREATE UNIQUE INDEX IF NOT EXISTS "clients_customer_no_key" ON "clients" USING btree ("customer_no");

-- Kundregistret ur sales/kunder_tvätteriet.xlsx (114 kunder).
INSERT INTO clients (customer_no, name, reminder_fee, name_truncated, notes) VALUES
  ('1000', 'Marriott', 350.00, false, NULL),
  ('1001', 'Arena Globen', 25.00, false, NULL),
  ('1002', 'Eatery', 25.00, false, NULL),
  ('1003', 'Aubergine', 30.00, false, NULL),
  ('1004', 'Babette', NULL, false, NULL),
  ('1005', 'Aveqia', NULL, false, NULL),
  ('1006', 'Belgobaren', 60.00, false, NULL),
  ('1007', 'Bentleys', NULL, false, NULL),
  ('1008', 'Blique Hotel', NULL, false, NULL),
  ('1009', 'Bromma Hotel', 60.00, false, NULL),
  ('1010', 'munchen', 80.00, false, NULL),
  ('1011', '108 Best Western', NULL, false, NULL),
  ('1012', 'Bålsta hotel', NULL, false, NULL),
  ('1013', 'Chefens Hotell', NULL, false, NULL),
  ('1014', 'Miss Clara', NULL, false, NULL),
  ('1015', 'Combo', NULL, false, NULL),
  ('1017', 'Cultura Crew', 20.00, false, NULL),
  ('1018', 'Ekerö hotel', NULL, false, NULL),
  ('1019', 'Fenix', NULL, false, NULL),
  ('1020', 'FH Fjäderholmen', NULL, false, NULL),
  ('1021', 'Freys hotel', 300.00, false, NULL),
  ('1022', 'Gamla Stan Hotell', NULL, false, NULL),
  ('1023', 'Giro', 10.00, false, NULL),
  ('1024', 'Gondolen', NULL, false, NULL),
  ('1025', 'Grow Hotel', 300.00, false, NULL),
  ('1026', 'Gyldene freden', 60.00, false, NULL),
  ('1027', 'Hemma Vasastan', 35.00, false, NULL),
  ('1028', 'Hornhuset', NULL, false, NULL),
  ('1029', 'J Hotell', NULL, false, NULL),
  ('1030', 'Skeppsholmen Hotell', NULL, false, NULL),
  ('1031', 'J Restaurang', NULL, false, NULL),
  ('1032', 'Balzac restaurang', 50.00, false, NULL),
  ('1033', 'Karlaplan Hotell', NULL, false, NULL),
  ('1034', 'Kista Hotel', NULL, false, NULL),
  ('1035', 'Lilla Brunn', NULL, false, NULL),
  ('1036', 'Luzette', 100.00, false, NULL),
  ('1037', 'Musikaliska', NULL, false, NULL),
  ('1038', 'Nacka Profil', NULL, false, NULL),
  ('1039', 'Nobis Hotel', NULL, false, NULL),
  ('1040', 'Opera', NULL, false, NULL),
  ('1041', 'Friends Arena', NULL, false, NULL),
  ('1042', 'Piatti restaurang', NULL, false, NULL),
  ('1043', 'PicPoc', NULL, false, NULL),
  ('1044', 'Queens Hotell', NULL, false, NULL),
  ('1045', 'Reimersholme Hotell', NULL, false, NULL),
  ('1046', 'Riche Restaurang', 250.00, false, NULL),
  ('1047', 'Rådmannen', 160.00, false, NULL),
  ('1048', 'Rökeriet', NULL, false, NULL),
  ('1049', 'Santo di Roma AB', NULL, false, NULL),
  ('1050', 'Sardin AB', NULL, false, NULL),
  ('1051', 'Scandinavian Hopitality', NULL, false, NULL),
  ('1052', 'Slagsta Hotell', NULL, false, NULL),
  ('1053', 'BBQ smokehouse', NULL, false, NULL),
  ('1054', 'Stallmästaregården ST', NULL, false, NULL),
  ('1055', 'Strandbryggan AB', NULL, false, NULL),
  ('1056', 'Strandvägen 1', NULL, false, NULL),
  ('1057', 'Svets Tech Sweden AB', NULL, false, NULL),
  ('1058', 'Sturehof', NULL, false, NULL),
  ('1059', 'Brillo', NULL, false, NULL),
  ('1060', 'Time Hotel', NULL, false, NULL),
  ('1061', 'Tranan Restaurang', NULL, false, NULL),
  ('1063', 'Turinge Hotel AB', NULL, false, NULL),
  ('1064', 'Ulriksdals Wärdshus AB', NULL, false, NULL),
  ('1065', 'NP', NULL, false, NULL),
  ('1066', 'Waxholms Hotell Aktiebol', NULL, true, NULL),
  ('1067', 'LA NONNA', NULL, false, NULL),
  ('1068', 'With Hotell', NULL, false, NULL),
  ('1069', 'Wasa Park Hotel', NULL, false, NULL),
  ('1070', 'Utbildningsförvaltningen', NULL, true, NULL),
  ('1071', 'Best Western Park City S', NULL, true, NULL),
  ('1072', 'ASPACE', NULL, false, NULL),
  ('1073', 'Comforta AB', NULL, false, NULL),
  ('1074', 'Motel L Älvsjö', NULL, false, NULL),
  ('1075', 'Motel L Hammarby', NULL, false, NULL),
  ('1076', 'Apartments By Ligula', NULL, false, NULL),
  ('1077', 'Central Hotel Profil', NULL, false, NULL),
  ('1078', 'Park City Hammarby Sjöst', NULL, true, 'Namnslut från källfilen: "...stern" – mitten saknas'),
  ('1079', 'Stadshotell Älvsjö AB', NULL, false, NULL),
  ('1080', 'Riddargatan Profilhotels', NULL, true, NULL),
  ('1081', 'Restaurant Ergo', NULL, false, NULL),
  ('1082', 'Stockholm Live', NULL, false, NULL),
  ('1083', 'ProSolar i Stockholm AB', NULL, false, NULL),
  ('1084', 'Kastellets Bed & Breakfa', NULL, true, NULL),
  ('1085', 'Nykvarns fest & hotell A', NULL, true, NULL),
  ('1086', 'Fabrikören', NULL, false, NULL),
  ('1087', 'Kasten Bistro AB', NULL, false, NULL),
  ('1088', 'Copine', NULL, false, NULL),
  ('1089', 'NK Copine', NULL, false, NULL),
  ('1090', 'Skogshöjd', NULL, false, NULL),
  ('1091', 'Waxholms Hotell', NULL, false, NULL),
  ('1092', 'Almnäs Event', NULL, false, NULL),
  ('1093', 'Södra teatern', NULL, false, NULL),
  ('1094', 'Hallwylska', NULL, false, NULL),
  ('1095', 'Mr French', NULL, false, NULL),
  ('1096', 'Artipelag', NULL, false, NULL),
  ('1097', 'ASPACE NYA', NULL, false, NULL),
  ('1098', 'Svenska stortvätten AB', NULL, false, NULL),
  ('1099', 'Hagastrand', NULL, false, NULL),
  ('1100', 'Hötorget Hotel', NULL, false, NULL),
  ('1101', 'Cafe Nizza', NULL, false, NULL),
  ('1102', 'Pizza', NULL, false, NULL),
  ('1103', 'italiano', NULL, false, NULL),
  ('1104', 'Rigoletto', NULL, false, NULL),
  ('1105', 'Bobergs Matsal', NULL, false, NULL),
  ('1106', 'Good Morning Sollentuna', NULL, false, NULL),
  ('1107', 'Sluss', 500.00, false, NULL),
  ('1108', 'La Civetta', NULL, false, NULL),
  ('1109', 'FESTIVITY', NULL, false, NULL),
  ('1110', 'Matateljén Slakthuset', NULL, false, NULL),
  ('1111', 'Boo Boo', NULL, false, NULL),
  ('1112', 'Sigtuna Hotel', NULL, false, NULL),
  ('1113', 'Kaggeholm', NULL, false, NULL),
  ('1114', 'RUBY', NULL, false, NULL),
  ('1115', 'Stockholm Meeting Select', NULL, true, NULL)
ON CONFLICT (customer_no) DO NOTHING;
