import type { Metadata } from "next";
import { Libre_Baskerville, Inter } from "next/font/google";
import "./globals.css";
import Header from "@/sections/Header";
import Footer from "@/sections/Footer";
import HomePageBubbles from "@/components/HomePageBubbles";
import { CartProvider } from "@/contexts/CartContext";
import { LanguageProvider } from "@/contexts/LanguageContext";

// Serif font for headings - elegant and refined
const libreBaskerville = Libre_Baskerville({
    variable: "--font-heading",
    subsets: ["latin"],
    weight: ["400", "700"],
    display: "swap",
});

// Sans-serif font for body text - clean and readable
const inter = Inter({
    variable: "--font-body",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="sv">
        <body className={`${libreBaskerville.variable} ${inter.variable}`}>
        <LanguageProvider>
            <CartProvider>
                <HomePageBubbles />
                <Header />
                {children}
                <Footer />
            </CartProvider>
        </LanguageProvider>
        </body>
        </html>
    );
}